- hosts: tag_Group_kubernetes
  remote_user: ubuntu
  become: true
  gather_facts: no
  pre_tasks:
    - name: install python2 because Ubuntu has python 3
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: Turn off swap
      command: swapoff -a

    - name: Add k8s packages key
      apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present

    - name: Add Kubernetes apt list
      copy: src=./files/kubernetes.list dest=/etc/apt/sources.list.d/kubernetes.list

    - name: Update cache
      apt: update_cache=yes

    - name: Upgrade
      apt: upgrade=dist

    - name: install docker
      apt: name=docker.io state=present

    - name: install kubelet
      apt: name=kubelet state=present

    - name: install kubectl
      apt: name=kubectl state=present

    - name: install kubeadm
      apt: name=kubeadm state=present

#    - name: install kubernetes-cni
#      apt: name=kubernetes-cni state=present

########################################################


- hosts: tag_Type_master
  remote_user: ubuntu
  become: true
  tasks:

    - name: Launch kubeadm in master
      #shell: "kubeadm init --apiserver-advertise-address {{ ansible_eth0.ipv4.address }} |grep 'kubeadm join'"
      shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 |grep 'kubeadm join'"
      register: output_kubeadm

    - set_fact:
        kubeadm_cmd: "{{output_kubeadm.stdout}}"
        
    - debug: msg="Output {{kubeadm_cmd}}"
   
    
- hosts: tag_Type_master
  remote_user: ubuntu
  tasks:    
    - name: Add config 
      shell: |
              mkdir -p /home/ubuntu/.kube
              sudo cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config 
              sudo chown $(id -u):$(id -g) /home/ubuntu/.kube/config
     
    
          
                    
                


#######################################################                

- hosts: tag_Group_kubernetes:&tag_Type_master
  remote_user: ubuntu
  tasks:

    - name:  Installing Flannel network plugin
      shell: |
              sudo sysctl net.bridge.bridge-nf-call-iptables=1
              kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
              

# until kube-dns pod comes up

    - pause:
        minutes: 3
    
               
     
                                                                
####################################################### 



- hosts: tag_Group_kubernetes:&tag_Type_slave
  remote_user: ubuntu
  become: true
  tasks:

    - set_fact:
        kubeadm: "{{hostvars[groups['tag_Type_master'][0]].kubeadm_cmd}}"
        
    - debug: msg="Output {{kubeadm}}"
    
    - name: Join to master
      command:  "{{ kubeadm }}"    


#######################################################   

- hosts: tag_Group_kubernetes:&tag_Type_master
  remote_user: ubuntu
  tasks:

    - name:  Installing simple nginx load balancer 
      shell: |
              kubectl run my-nginx --image=nginx --replicas=2 --port=80
              kubectl expose deployment my-nginx --port=80 --type=LoadBalancer

               

                                    
            
